(library
 (name my_hardcaml_riscv)
 (libraries hardcaml)
 (preprocess (pps ppx_hardcaml))
)

(executable
 (name top)
 (libraries hardcaml my_hardcaml_riscv)
 (preprocess (pps ppx_hardcaml))
)

(rule
 (targets rv32i_simple.v)
 (deps top.exe)
 (action
  (with-stdout-to rv32i_simple.v
   (run ./top.exe))))
